sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abdelrhmansafwat/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true abdelrhmansafwat/docker-react npm run test
